runtime: python37
env: standard
instance_class: F2
entrypoint: gunicorn -b :$PORT main:app

automatic_scaling:
  min_instances: 1
  max_instances: 1
  min_idle_instances: 0
  max_idle_instances: 1
  min_pending_latency: 3000ms
  max_pending_latency: automatic

handlers:

- url: /static
  static_dir: static

- url: /.*
  script: auto
